# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Workplace/Vivado/fuck/fuck.srcs/sources_1/bd/fuck/ip/fuck_axi_mem_intercon_imp_xbar_0/fuck_axi_mem_intercon_imp_xbar_0.xci
# IP: The module: 'fuck_axi_mem_intercon_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Workplace/Vivado/fuck/fuck.gen/sources_1/bd/fuck/ip/fuck_axi_mem_intercon_imp_xbar_0/fuck_axi_mem_intercon_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fuck_axi_mem_intercon_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: f:/Workplace/Vivado/fuck/fuck.srcs/sources_1/bd/fuck/ip/fuck_axi_mem_intercon_imp_xbar_0/fuck_axi_mem_intercon_imp_xbar_0.xci
# IP: The module: 'fuck_axi_mem_intercon_imp_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Workplace/Vivado/fuck/fuck.gen/sources_1/bd/fuck/ip/fuck_axi_mem_intercon_imp_xbar_0/fuck_axi_mem_intercon_imp_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fuck_axi_mem_intercon_imp_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
