# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/fuck.xdc

# Block Designs: bd/fuck/fuck.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fuck || ORIG_REF_NAME==fuck} -quiet] -quiet

# IP: bd/fuck/ip/fuck_processing_system7_0_0/fuck_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fuck_processing_system7_0_0 || ORIG_REF_NAME==fuck_processing_system7_0_0} -quiet] -quiet

# IP: bd/fuck/ip/fuck_ddr3_hdmi_ov5640_0_0/fuck_ddr3_hdmi_ov5640_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fuck_ddr3_hdmi_ov5640_0_0 || ORIG_REF_NAME==fuck_ddr3_hdmi_ov5640_0_0} -quiet] -quiet

# IP: bd/fuck/ip/fuck_v_vid_in_axi4s_0_0/fuck_v_vid_in_axi4s_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fuck_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==fuck_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/fuck/ip/fuck_clk_wiz_0_0/fuck_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fuck_clk_wiz_0_0 || ORIG_REF_NAME==fuck_clk_wiz_0_0} -quiet] -quiet

# IP: bd/fuck/ip/fuck_util_vector_logic_0_0/fuck_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fuck_util_vector_logic_0_0 || ORIG_REF_NAME==fuck_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/fuck/ip/fuck_axi_vdma_0_0/fuck_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fuck_axi_vdma_0_0 || ORIG_REF_NAME==fuck_axi_vdma_0_0} -quiet] -quiet

# IP: bd/fuck/ip/fuck_v_tc_0_0/fuck_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fuck_v_tc_0_0 || ORIG_REF_NAME==fuck_v_tc_0_0} -quiet] -quiet

# IP: bd/fuck/ip/fuck_v_axi4s_vid_out_0_0/fuck_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fuck_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==fuck_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/fuck/ip/fuck_util_vector_logic_1_0/fuck_util_vector_logic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fuck_util_vector_logic_1_0 || ORIG_REF_NAME==fuck_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/fuck/ip/fuck_hdmi_trans_0_0/fuck_hdmi_trans_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fuck_hdmi_trans_0_0 || ORIG_REF_NAME==fuck_hdmi_trans_0_0} -quiet] -quiet

# IP: bd/fuck/ip/fuck_xlconstant_0_0/fuck_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fuck_xlconstant_0_0 || ORIG_REF_NAME==fuck_xlconstant_0_0} -quiet] -quiet

# IP: bd/fuck/ip/fuck_axi_smc_0/fuck_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fuck_axi_smc_0 || ORIG_REF_NAME==fuck_axi_smc_0} -quiet] -quiet

# IP: bd/fuck/ip/fuck_rst_ps7_0_50M_0/fuck_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fuck_rst_ps7_0_50M_0 || ORIG_REF_NAME==fuck_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/fuck/ip/fuck_axi_mem_intercon_imp_xbar_0/fuck_axi_mem_intercon_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fuck_axi_mem_intercon_imp_xbar_0 || ORIG_REF_NAME==fuck_axi_mem_intercon_imp_xbar_0} -quiet] -quiet

# IP: bd/fuck/ip/fuck_axi_mem_intercon_0/fuck_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fuck_axi_mem_intercon_0 || ORIG_REF_NAME==fuck_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/fuck/ip/fuck_axi_mem_intercon_imp_auto_pc_0/fuck_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fuck_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==fuck_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# XDC: f:/Workplace/Vivado/fuck/fuck.gen/sources_1/bd/fuck/fuck_ooc.xdc
